POST http://127.0.0.1:8080/rpc/send/await HTTP/1.1
Content-Type: application/json

{
  "message": "wechaty-message",
  "receiver": {
    "name": "name-or-alias",
    "isAlias": false,
    "category": "friend"
  },
  "token": "receiver-token"
}
