POST http://127.0.0.1:8080/rpc/forward HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "id": 8926017981181411,
  "receiver": {
    "name": "name-or-alias",
    "isAlias": false,
    "category": "friend"
  },
  "token": "receiver-token"
}
