POST http://127.0.0.1:8002/rpc/send HTTP/1.1
content-type: application/json;charset=UTF-8

{
  "message": "text-and-small-sticker",
  "receiver": {
    "name": "name-or-alias",
    "isAlias": false,
    "category": "friend"
  },
  "rpcToken": "wechatconnector70xzkbtynmtpr7apu7w7e1hroaieonx0vyepg7yimdys0bf2s"
}
