POST http://127.0.0.1:8080/rpc/log HTTP/1.1
Content-Type: application/json; charset=UTF-8

{"id":6433796102126135,"level":"info","type":"wechat-worker.listener.http.listen","content":{"port":8080},"timestamp":1592494055696,"token":"wechaty-sender-log-0"}
